modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "evernight"
version = "${version}"
displayName = "Evernight"
authors = "waucka"
description = '''
Make the night last forever without stopping time
'''
#logoFile = ""

[[dependencies.evernight]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.evernight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.evernight]]
modId = "architectury"
mandatory = true
versionRange = "[8.2.89,)"
ordering = "AFTER"
side = "BOTH"
